- name: auto_funding
  report_type: dwh2notification
  s3_sources:
    main_docum_inc: data/abs-cft/raw/main_docum/inc
    actions_history: data/core_auto_topup/ods_v2/core_auto_topup/public/actions_history/latest
    autofund_actions_history: data/core_auto_topup/ods_v2/core_auto_topup/public/autofund_actions_history/latest
  # s3_bucket: dwh-bank-recon-s3-prod
  filename_pattern: "users/lerayatsevich/rec/Сверка по автопоплнениям и автофондированию за {DT}.csv"
  sql_query: auto_funding.sql
  indicator_type: failure
  indicator_name: 'auto_funding/{DT}'
  DT: -1
  ticket:
    queue: SVERKIDWH
    summary:  Сверка по автопоплнениям и автофондированию за {DT} не успешна
    description: Расхождения обнаружены, файл приложен.
    assignee: e-v-samohvalo
    followers:
      - karpachevata
    type:
      name: Task
    priority:
      name: Critical 
  attach_type: [ticket]
  attachment:
    - sql_condition: select count(*)>0 from result
  email_on_failture:
    subject: Сверка по автопоплнениям и автофондированию за {DT} успешна
    recipients: 
      - lerayatsevich@yandex-team.ru
      - karpachevata@yandex-team.ru
      - deposit@bank.yandex.ru
    body: Расхождений не обнаружено.
