- name: abs_cft_core_accounts
  report_type: dwh2notification
  s3_sources:
    product: data/abs-cft/ods/product/snapshots/dt={today}
    depn: data/abs-cft/ods/depn/snapshots/dt={today}
    vid_deposit: data/abs-cft/ods/vid_deposit/snapshots/dt={today}
    com_status_prd: data/abs-cft/ods/com_status_prd/snapshots/dt={today}
    ac_fin: data/abs-cft/ods/ac_fin/snapshots/dt={today}
    account_cft: data/abs-cft/ods/account/snapshots/dt={today}
    account_core: data/core_savings_account/ods/core_savings_account/public/account/latest
    operations: data/core_registers_data/ods/core-registers-data/operations/latest
    account_balance: data/cdm/account_balance

  
  filename_pattern: "data/reconciliation/Сверка по накопительным счетам ABS-CFT/{DT_SLASH}/Сверка по накопительным счетам ABS-CFT за {DT}.xlsx"
  sql_query: abs_cft_core_accounts.sql
  indicator_type: failure
  indicator_name: 'abs_cft_core_accounts/{DT}'
  DT: -1
  attach_type: [email, email_text]
  attachment:
    - sql_condition: select count(*)>0 from result
      add_text: abs_cft_core_accounts.j2
      sql_fill_template: |
        select 
          sum (case when dif_type = 'lost_ftc' then 1 else 0 end) as cnt_lost_ftc
          ,sum (case when dif_type = 'lost_cft' then 1 else 0 end) as cnt_lost_cft
          ,sum (case when dif_type = 'dif_status' then 1 else 0 end) as cnt_dif_status
          ,sum (case when dif_type = 'dif_open_date' then 1 else 0 end) as cnt_dif_open_date
          ,sum (case when dif_type = 'dif_close_date' then 1 else 0 end) as cnt_dif_close_date
          ,sum (case when dif_type = 'dif_open_null' then 1 else 0 end) as cnt_dif_open_null
          ,sum (case when dif_type = 'diff_balance' then 1 else 0 end) as cnt_diff_balance
        from result
  email:
    subject: Сверка по накопительным счетам ABS-CFT за {DT} не успешна
    recipients: 
      - ipochitalkin@yandex-team.ru
    body: Сверка по накопительным счетам ABS-CFT за {DT} не успешна
  email_on_failture:
    subject: Сверка по накопительным счетам ABS-CFT за {DT} успешна
    recipients: 
      - ipochitalkin@yandex-team.ru
    body: Расхождений не обнаружено.