- name: fake_clears
  report_type: dwh2notification
  s3_sources:
    bo_txn: data/solar-v2/ods/pay-iss-bo/bo_txn/snapshots/dt={today}
    bo_txn_type: data/solar-v2/ods/pay-iss-bo/bo_txn_type/snapshots/dt={today}
    bo_accessor: data/solar-v2/ods/pay-iss-bo/bo_accessor/snapshots/dt={today}
    bo_accessor_type: data/solar-v2/ods/pay-iss-bo/bo_accessor_type/snapshots/dt={today}
    rt_system: data/solar-v2/ods/pay-iss-bo/rt_system/snapshots/dt={today}
    cards_bo_txn: data/solar-v2/ods/cards-iss-bo/bo_txn/snapshots/dt={today}
    cards_bo_txn_type: data/solar-v2/ods/cards-iss-bo/bo_txn_type/snapshots/dt={today}
    cards_rt_system: data/solar-v2/ods/cards-iss-bo/rt_system/snapshots/dt={today}
    authorization_transactions: data/core_auth_doc_data/ods/core-auth-doc-data/authorization_transactions/latest
    financial_transactions: data/core_auth_doc_data/ods/core-auth-doc-data/financial_transactions/latest
  # s3_bucket: изменить на проде
  filename_pattern: "operations/reconciliation/Сверка fake clears с клирингом/{DT_SLASH}/Сверка fake clears с клирингом {DT} ({DTTM}).xlsx"
  sql_query: ps_mir_fake_clears.sql
  indicator_type: failure
  indicator_name: 'ps_mir_fake_clears/{DT}'
  DT: -2
  ticket:
    &insert_ticket
    queue: FINDWHNPE
    summary:  Сверка fake clears с клирингом за {DT} не успешна
    description: Расхождения обнаружены, файл в почте.
    assignee: lerayatsevich
    type:
      name: Task
    priority:
      name: Critical 
  attach_type: [email]
  attachment:
    - sql_condition: select count(*) from result
  email:
    &insert_email
    subject:  Сверка fake clears с клирингом за {DT} не успешна
    recipients: 
      - lerayatsevich@yandex-team.ru
    body: Расхождения обнаружены, файл во вложении.
  email_on_failture:
    &insert_email_on_failture
    subject: Сверка fake clears с клирингом за {DT} успешна
    recipients: 
      - lerayatsevich@yandex-team.ru
    body: Расхождений не обнаружено.
  gp_table:
    table_name: ps_mir_fake_clears
    table_schema: reconciliation
- name: transaction_duplicate
  report_type: dwh2notification
  s3_sources:
    bo_txn: data/solar-v2/ods/pay-iss-bo/bo_txn/snapshots/dt={today}
    bo_txn_type: data/solar-v2/ods/pay-iss-bo/bo_txn_type/snapshots/dt={today}
    bo_accessor: data/solar-v2/ods/pay-iss-bo/bo_accessor/snapshots/dt={today}
    bo_accessor_type: data/solar-v2/ods/pay-iss-bo/bo_accessor_type/snapshots/dt={today}
    rt_system: data/solar-v2/ods/pay-iss-bo/rt_system/snapshots/dt={today}
    cards_bo_txn: data/solar-v2/ods/cards-iss-bo/bo_txn/snapshots/dt={today}
    cards_bo_txn_type: data/solar-v2/ods/cards-iss-bo/bo_txn_type/snapshots/dt={today}
    cards_rt_system: data/solar-v2/ods/cards-iss-bo/rt_system/snapshots/dt={today}
    authorization_transactions: data/core_auth_doc_data/ods/core-auth-doc-data/authorization_transactions/latest
    financial_transactions: data/core_auth_doc_data/ods/core-auth-doc-data/financial_transactions/latest
    main_docum_inc: data/abs-cft/raw/main_docum/inc
  filename_pattern: "operations/reconciliation/Сверка на дубли транзакций/{DT_SLASH}/Сверка на дубли транзакций {DT} ({DTTM}).xlsx"
  sql_query: ps_mir_transaction_duplicate.sql
  indicator_type: failure
  indicator_name: 'ps_mir_transaction_duplicate/{DT}'
  DT: -2
  ticket:
    <<: *insert_ticket
    summary:  Сверка на дубли транзакций за {DT} не успешна
  attach_type: [email]
  attachment:
    - sql_condition: select count(*) from result
  email:
    <<: *insert_email
    subject:  Сверка на дубли транзакций за {DT} не успешна
  email_on_failture:
    <<: *insert_email_on_failture
    subject: Сверка на дубли транзакций за {DT} успешна
  gp_table:
    table_name: ps_mir_transaction_duplicate
    table_schema: reconciliation

- name: card_transactions
  report_type: dwh2notification
  s3_sources:
    bo_txn: data/solar-v2/ods/pay-iss-bo/bo_txn/snapshots/dt={today}
    bo_txn_type: data/solar-v2/ods/pay-iss-bo/bo_txn_type/snapshots/dt={today}
    bo_accessor: data/solar-v2/ods/pay-iss-bo/bo_accessor/snapshots/dt={today}
    bo_accessor_type: data/solar-v2/ods/pay-iss-bo/bo_accessor_type/snapshots/dt={today}
    bo_agreement: data/solar-v2/ods/pay-iss-bo/bo_agreement/snapshots/dt={today}
    rt_system: data/solar-v2/ods/pay-iss-bo/rt_system/snapshots/dt={today}
    main_docum_inc: data/abs-cft/raw/main_docum/inc
    product: data/abs-cft/ods/product/snapshots/dt={today}
    hoz_op_acc: data/abs-cft/ods/hoz_op_acc/snapshots/dt={today}
    ya_product: data/abs-cft/ods/ya_product/snapshots/dt={today}
  filename_pattern: "operations/reconciliation/Сверка по карточным транзакциям с документами АБС/{DT_SLASH}/Сверка по карточным транзакциям с документами АБС за {DT} ({DTTM}).xlsx"
  sql_query: ps_mir_card_transactions.sql
  indicator_type: failure
  indicator_name: 'ps_mir_card_transactions/{DT}'
  DT: -2
  ticket:
    <<: *insert_ticket
    summary:  Сверка по карточным транзакциям с документами АБС за {DT} не успешна
  attach_type: [email]
  attachment:
    - sql_condition: select count(*) from result
  email:
    <<: *insert_email
    subject:  Сверка по карточным транзакциям с документами АБС за {DT} не успешна
  email_on_failture:
    <<: *insert_email_on_failture
    subject: Сверка по карточным транзакциям с документами АБС за {DT} успешна
  gp_table:
    table_name: ps_mir_card_transactions
    table_schema: reconciliation

- name: credit_transactions
  report_type: dwh2notification
  # s3_bucket: processing-dwh-npe
  s3_sources:
    cards_bo_txn: data/solar-v2/ods/cards-iss-bo/bo_txn/snapshots/dt={today}
    cards_bo_txn_type: data/solar-v2/ods/cards-iss-bo/bo_txn_type/snapshots/dt={today}
    cards_bo_agreement: data/solar-v2/ods/cards-iss-bo/bo_agreement/snapshots/dt={today}
    cards_rt_system: data/solar-v2/ods/cards-iss-bo/rt_system/snapshots/dt={today}
    authorization_transactions: data/core_auth_doc_data/ods/core-auth-doc-data/authorization_transactions/latest
    financial_transactions: data/core_auth_doc_data/ods/core-auth-doc-data/financial_transactions/latest
    main_docum_inc: data/abs-cft/raw/main_docum/inc
    product: data/abs-cft/ods/product/snapshots/dt={today}
    hoz_op_acc: data/abs-cft/ods/hoz_op_acc/snapshots/dt={today}
    ya_product: data/abs-cft/ods/ya_product/snapshots/dt={today}
  filename_pattern: "operations/reconciliation/Сверка по кредитным транзакциям с документами АБС/{DT_SLASH}/Сверка по кредитным транзакциям с документами АБС за {DT} ({DTTM}).xlsx"
  sql_query: ps_mir_credit_transactions.sql
  indicator_type: failure
  indicator_name: 'ps_mir_credit_transactions/{DT}'
  DT: -2
  ticket:
    <<: *insert_ticket
    summary:  Сверка по кредитным транзакциям с документами АБС за {DT} не успешна
  attach_type: [email]
  attachment:
    - sql_condition: select count(*) from result
  email:
    <<: *insert_email
    subject:  Сверка по кредитным транзакциям с документами АБС за {DT} не успешна
  email_on_failture:
    <<: *insert_email_on_failture
    subject: Сверка по кредитным транзакциям с документами АБС за {DT} успешна
  gp_table:
    table_name: ps_mir_credit_transactions
    table_schema: reconciliation
    